/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package Code.Name.Flamboyan.SwingMakeOver;

/* Success is My Journey not a Destination :)
 * DILARANG MENGHAPUS ATAU MENGEDIT COPYRIGHT INI.
 * 
 * Copyright 2011 serendipity.10they@gmail.com. 
 * Licensed GNU/GPL
 * All rights reserved.
 * 
 * Semua isi dalam file ini adalah hak milik dari Presdir Atanasius Tendy.
 * Anda tidak diperkenankan untuk menggunakan file atau mengubah file
 * ini kecuali anda tidak menghapus atau merubah Lisensi ini.
 * 
 * File ini dibuat menggunakan :
 * IDE        : NetBeans 7.0.1
 * NoteBook   : Asus K42Jc Versatile Performance
 * OS         : Windows 7 Ultimate
 * Java       : Java 1.7
 * 
 * Program Intentity :
 * Code Name  :
 * Code Created on Jan 9, 2012, 10:52:29 AM
 * @author PresdirTendy
 */
public class NewJFrame extends javax.swing.JFrame {

    /** Creates new form NewJFrame */
    public NewJFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGradientColor1 = new Code.Name.Flamboyan.SwingMakeOver.ButtonGradientColor();
        panelBackGroundTree1 = new Code.Name.Flamboyan.SwingMakeOver.PanelBackGroundTree();
        buttonGradientColor2 = new Code.Name.Flamboyan.SwingMakeOver.ButtonGradientColor();
        buttonImageGlass1 = new Code.Name.Flamboyan.SwingMakeOver.ButtonImageGlass();
        buttonGradientColor3 = new Code.Name.Flamboyan.SwingMakeOver.ButtonGradientColor();
        buttonImageGlass2 = new Code.Name.Flamboyan.SwingMakeOver.ButtonImageGlass();
        buttonRoundRect1 = new Code.Name.Flamboyan.SwingMakeOver.ButtonRoundRect();
        gradientPanel1 = new Code.Name.Flamboyan.SwingMakeOver.GradientPanel();
        panelAlphaRect1 = new Code.Name.Flamboyan.SwingMakeOver.PanelAlphaRect();
        panelBackgroundHome1 = new Code.Name.Flamboyan.SwingMakeOver.PanelBackgroundHome();
        panelImage1 = new Code.Name.Flamboyan.SwingMakeOver.PanelImage();
        panelGlass1 = new Code.Name.Flamboyan.SwingMakeOver.PanelGlass();
        panelImage2 = new Code.Name.Flamboyan.SwingMakeOver.PanelImage();
        panelGradientUpDown2Color1 = new Code.Name.Flamboyan.SwingMakeOver.PanelGradientUpDown2Color();

        buttonGradientColor1.setText("buttonGradientColor1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGradientColor2.setText("buttonGradientColor2");

        buttonImageGlass1.setText("buttonImageGlass1");

        buttonGradientColor3.setText("buttonGradientColor3");

        buttonImageGlass2.setText("buttonImageGlass2");

        buttonRoundRect1.setText("buttonRoundRect1");

        javax.swing.GroupLayout gradientPanel1Layout = new javax.swing.GroupLayout(gradientPanel1);
        gradientPanel1.setLayout(gradientPanel1Layout);
        gradientPanel1Layout.setHorizontalGroup(
            gradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        gradientPanel1Layout.setVerticalGroup(
            gradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelBackgroundHome1Layout = new javax.swing.GroupLayout(panelBackgroundHome1);
        panelBackgroundHome1.setLayout(panelBackgroundHome1Layout);
        panelBackgroundHome1Layout.setHorizontalGroup(
            panelBackgroundHome1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelBackgroundHome1Layout.setVerticalGroup(
            panelBackgroundHome1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelAlphaRect1Layout = new javax.swing.GroupLayout(panelAlphaRect1);
        panelAlphaRect1.setLayout(panelAlphaRect1Layout);
        panelAlphaRect1Layout.setHorizontalGroup(
            panelAlphaRect1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlphaRect1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBackgroundHome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );
        panelAlphaRect1Layout.setVerticalGroup(
            panelAlphaRect1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAlphaRect1Layout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addComponent(panelBackgroundHome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelGlass1Layout = new javax.swing.GroupLayout(panelGlass1);
        panelGlass1.setLayout(panelGlass1Layout);
        panelGlass1Layout.setHorizontalGroup(
            panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelGlass1Layout.setVerticalGroup(
            panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelImage2Layout = new javax.swing.GroupLayout(panelImage2);
        panelImage2.setLayout(panelImage2Layout);
        panelImage2Layout.setHorizontalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelImage2Layout.setVerticalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelGradientUpDown2Color1Layout = new javax.swing.GroupLayout(panelGradientUpDown2Color1);
        panelGradientUpDown2Color1.setLayout(panelGradientUpDown2Color1Layout);
        panelGradientUpDown2Color1Layout.setHorizontalGroup(
            panelGradientUpDown2Color1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelGradientUpDown2Color1Layout.setVerticalGroup(
            panelGradientUpDown2Color1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelBackGroundTree1Layout = new javax.swing.GroupLayout(panelBackGroundTree1);
        panelBackGroundTree1.setLayout(panelBackGroundTree1Layout);
        panelBackGroundTree1Layout.setHorizontalGroup(
            panelBackGroundTree1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackGroundTree1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(panelBackGroundTree1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelBackGroundTree1Layout.createSequentialGroup()
                        .addGroup(panelBackGroundTree1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonImageGlass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonGradientColor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(panelImage2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBackGroundTree1Layout.createSequentialGroup()
                        .addGroup(panelBackGroundTree1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelGlass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelGradientUpDown2Color1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panelBackGroundTree1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBackGroundTree1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonImageGlass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonGradientColor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBackGroundTree1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(panelBackGroundTree1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBackGroundTree1Layout.createSequentialGroup()
                                .addComponent(buttonRoundRect1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(113, 113, 113))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBackGroundTree1Layout.createSequentialGroup()
                                .addComponent(panelAlphaRect1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58))))))
        );
        panelBackGroundTree1Layout.setVerticalGroup(
            panelBackGroundTree1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackGroundTree1Layout.createSequentialGroup()
                .addGroup(panelBackGroundTree1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBackGroundTree1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(buttonGradientColor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(buttonImageGlass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBackGroundTree1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelBackGroundTree1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonGradientColor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelImage2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(panelBackGroundTree1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelBackGroundTree1Layout.createSequentialGroup()
                        .addGroup(panelBackGroundTree1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelBackGroundTree1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelGlass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(gradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelBackGroundTree1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(panelAlphaRect1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelBackGroundTree1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(buttonRoundRect1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(15, Short.MAX_VALUE))
                    .addGroup(panelBackGroundTree1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonImageGlass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(panelGradientUpDown2Color1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        getContentPane().add(panelBackGroundTree1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Code.Name.Flamboyan.SwingMakeOver.ButtonGradientColor buttonGradientColor1;
    private Code.Name.Flamboyan.SwingMakeOver.ButtonGradientColor buttonGradientColor2;
    private Code.Name.Flamboyan.SwingMakeOver.ButtonGradientColor buttonGradientColor3;
    private Code.Name.Flamboyan.SwingMakeOver.ButtonImageGlass buttonImageGlass1;
    private Code.Name.Flamboyan.SwingMakeOver.ButtonImageGlass buttonImageGlass2;
    private Code.Name.Flamboyan.SwingMakeOver.ButtonRoundRect buttonRoundRect1;
    private Code.Name.Flamboyan.SwingMakeOver.GradientPanel gradientPanel1;
    private Code.Name.Flamboyan.SwingMakeOver.PanelAlphaRect panelAlphaRect1;
    private Code.Name.Flamboyan.SwingMakeOver.PanelBackGroundTree panelBackGroundTree1;
    private Code.Name.Flamboyan.SwingMakeOver.PanelBackgroundHome panelBackgroundHome1;
    private Code.Name.Flamboyan.SwingMakeOver.PanelGlass panelGlass1;
    private Code.Name.Flamboyan.SwingMakeOver.PanelGradientUpDown2Color panelGradientUpDown2Color1;
    private Code.Name.Flamboyan.SwingMakeOver.PanelImage panelImage1;
    private Code.Name.Flamboyan.SwingMakeOver.PanelImage panelImage2;
    // End of variables declaration//GEN-END:variables

}
