/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.yud.ui;

import com.init.tools.DaoFactory;
import com.init.tools.PrintReport;
import com.yud.angsuran.Angsuran;
import com.yud.angsuran.AngsuranBulananTabelModel;
import com.yud.stb.BuktiPesanan;
import com.yud.stb.BuktiPesananTabelModel;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.RowSorter;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import net.sf.jasperreports.components.barbecue.BarcodeProviders;

/**
 *
 * @author legollas
 */
public class AngsuranBulanan extends javax.swing.JFrame {

    private RowSorter<TableModel> sorter = null;
    private TableRowSorter<TableModel> sorter2 = null;

    /**
     * Creates new form AngsuranBulanan
     */
    public AngsuranBulanan() {
        initComponents();
        tglAngsuran.setDate(new GregorianCalendar().getTime());
        setLocationRelativeTo(null);
        loadForm();
    }

    private void clearfild() {
        loadForm();
        txtkodeangsuran.setText("");
        txtkodebp.setText("");
        txtjumlah.setText("");
        tglAngsuran.setDate(new GregorianCalendar().getTime());
    }

    private void loadForm() {
        jDesktopPane1.setVisible(true);
        jDesktopPane3.setVisible(false);
        txtFilter.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtkodeangsuran = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tglAngsuran = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        txtkodebp = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtjumlah = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelAngsurannya = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        comboAngsuran = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtFilter = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtsisaberjalanlab = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtmakslab = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txttotalbplab = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txttotalangsuranlab = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtbulannalab = new javax.swing.JLabel();
        jDesktopPane3 = new javax.swing.JDesktopPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        filterBP = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelBP = new javax.swing.JTable();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 204));
        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ANGSURAN BULANAN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(412, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(374, 374, 374))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jDesktopPane1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 60));

        jLabel5.setText("Kode Angsuran");

        txtkodeangsuran.setEditable(false);

        jButton7.setText("Cari");

        jLabel6.setText("Tanggal");

        jLabel2.setText("Kode BP");

        txtkodebp.setEditable(false);
        txtkodebp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtkodebpMouseClicked(evt);
            }
        });
        txtkodebp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkodebpActionPerformed(evt);
            }
        });
        txtkodebp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtkodebpKeyPressed(evt);
            }
        });

        jButton8.setText("Cari");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel4.setText("Jumlah Uang");

        tabelAngsurannya.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelAngsurannya.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelAngsurannyaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelAngsurannya);

        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Angsuran Ke");

        comboAngsuran.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        comboAngsuran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Angsuran 1", "Angsuran 2", "Angsuran 3", "Angsuran 4", "Angsuran 5", "Angsuran 6", "Angsuran 7", "Angsuran 8", "Angsuran 9", "Angsuran 10" }));

        jLabel7.setText("Cari");

        txtFilter.setEnabled(false);

        jButton2.setText("Tutup");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Batal");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Cetak");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Refresh");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Angsuran");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Ke");

        txtsisaberjalanlab.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtsisaberjalanlab.setText(".......");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Dari");

        txtmakslab.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtmakslab.setText("........");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Total BP");

        txttotalbplab.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txttotalbplab.setText("..................");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Total Angsuran");

        txttotalangsuranlab.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txttotalangsuranlab.setText(".................");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Angsuran Bulanan : Rp.");

        txtbulannalab.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtbulannalab.setText("txtbulanan");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtkodeangsuran, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtkodebp, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tglAngsuran, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(comboAngsuran, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFilter))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addGap(14, 14, 14)
                                .addComponent(txtsisaberjalanlab))
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtmakslab)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txttotalbplab, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txttotalangsuranlab, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtbulannalab, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtkodeangsuran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(jButton7)
                        .addComponent(jLabel2)
                        .addComponent(txtkodebp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton8)
                        .addComponent(jLabel4)
                        .addComponent(txtjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tglAngsuran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboAngsuran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(txtsisaberjalanlab)
                    .addComponent(jLabel11)
                    .addComponent(txtmakslab)
                    .addComponent(jLabel10)
                    .addComponent(txttotalbplab)
                    .addComponent(jLabel12)
                    .addComponent(txttotalangsuranlab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtbulannalab))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jDesktopPane1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 57, 980, 450));

        jDesktopPane3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 204, 204));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("DAFTAR BUKTI PESANAN");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(435, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(365, 365, 365))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDesktopPane3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, -1));

        jLabel16.setText("Cari");

        filterBP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                filterBPKeyTyped(evt);
            }
        });

        TabelBP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelBP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelBPMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TabelBP);

        jButton9.setText("Tutup");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Pilih");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 946, Short.MAX_VALUE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(filterBP))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(filterBP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(jButton10))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jDesktopPane3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 980, 340));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jDesktopPane1))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jDesktopPane3))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 13, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jDesktopPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 140, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtkodebpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtkodebpKeyPressed
        // TODO add your handling code here:
        String kode = txtkodebp.getText();

    }//GEN-LAST:event_txtkodebpKeyPressed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        jDesktopPane3.setVisible(true);
        jDesktopPane1.setVisible(false);
        String kode = txtkodebp.getText();
        BuktiPesanan bp = DaoFactory.getBuktiPesananDao().getBuktiPesananByKodeBP(kode);
        txtsisaberjalanlab.setText(String.valueOf(bp.getSisa2()));
        txtmakslab.setText(String.valueOf(bp.getSisa()));
        txttotalbplab.setText(String.valueOf(bp.getTotal()));
        showBP();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void filterBPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filterBPKeyTyped
        // TODO add your handling code here:
        String text = filterBP.getText();
        if (text.length() == 0) {
            sorter2.setRowFilter(null);
            System.out.println("p");
        } else {
            System.out.println("y");
            sorter2.setRowFilter(RowFilter.regexFilter(text));
        }
    }//GEN-LAST:event_filterBPKeyTyped

    private void TabelBPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelBPMouseClicked
        // TODO add your handling code here:
        int row = TabelBP.getSelectedRow();
        if (row >= 0) {
            String kodebp = TabelBP.getValueAt(row, 9).toString();
            txtkodebp.setText(kodebp);
            Angsuran a = DaoFactory.getAngsuranDao().getAngsuranByKodeBP(kodebp);
            txtkodeangsuran.setText(a.getKodeAngsuran());
            jDesktopPane3.setVisible(false);
            jDesktopPane1.setVisible(true);
            showAngsuranBP(kodebp);
            txtkodebp.requestFocus();
        }
    }//GEN-LAST:event_TabelBPMouseClicked

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        jDesktopPane3.setVisible(false);
        jDesktopPane1.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String kodeans = txtkodeangsuran.getText();
        String kodebp = txtkodebp.getText();
        String jumlah = txtjumlah.getText();
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        String tanggalnya = df.format(tglAngsuran.getDate());
        String angsuranke = comboAngsuran.getSelectedItem().toString();
        if (angsuranke.equalsIgnoreCase("Angsuran 1")) {
            if (txtkodeangsuran.getText() != "") {
                com.yud.angsuran.AngsuranBulanan ab = new com.yud.angsuran.AngsuranBulanan();
                ab.setKodeans(kodeans);
                ab.setKodebp(kodebp);
                ab.setAngsuran1(jumlah);
                ab.setJumlah(Integer.parseInt(jumlah));
                ab.setTgl1(tanggalnya);
                ab.setTanggal(tanggalnya);
                ab.setAngsuranke(angsuranke);
                DaoFactory.getAngsuranBulananDao().resetSpaceDateAns(kodebp);
                DaoFactory.getAngsuranBulananDao().insertdetailangsuran(ab);
                DaoFactory.getAngsuranBulananDao().UpdateAngsuranBulanan1(ab);
                DaoFactory.getAngsuranDao().updateSisaAngsuran(kodebp);
            }
        } else if (angsuranke.equalsIgnoreCase("Angsuran 2")) {
            if (txtkodeangsuran.getText() != "") {
                com.yud.angsuran.AngsuranBulanan ab = new com.yud.angsuran.AngsuranBulanan();
                ab.setKodeans(kodeans);
                ab.setKodebp(kodebp);
                ab.setAngsuran2(jumlah);
                ab.setJumlah(Integer.parseInt(jumlah));
                ab.setTanggal(tanggalnya);
                ab.setTgl2(tanggalnya);
                ab.setAngsuranke(angsuranke);
                DaoFactory.getAngsuranBulananDao().resetSpaceDateAns(kodebp);
                DaoFactory.getAngsuranBulananDao().insertdetailangsuran(ab);
                DaoFactory.getAngsuranBulananDao().UpdateAngsuranBulanan2(ab);
                DaoFactory.getAngsuranDao().updateSisaAngsuran(kodebp);
            }
        } else if (angsuranke.equalsIgnoreCase("Angsuran 3")) {
            if (txtkodeangsuran.getText() != "") {
                com.yud.angsuran.AngsuranBulanan ab = new com.yud.angsuran.AngsuranBulanan();
                ab.setKodeans(kodeans);
                ab.setKodebp(kodebp);
                ab.setAngsuran3(jumlah);
                ab.setJumlah(Integer.parseInt(jumlah));
                ab.setTgl3(tanggalnya);
                ab.setTanggal(tanggalnya);
                ab.setAngsuranke(angsuranke);
                DaoFactory.getAngsuranBulananDao().resetSpaceDateAns(kodebp);
                DaoFactory.getAngsuranBulananDao().insertdetailangsuran(ab);
                DaoFactory.getAngsuranBulananDao().UpdateAngsuranBulanan3(ab);
                DaoFactory.getAngsuranDao().updateSisaAngsuran(kodebp);
            }
        } else if (angsuranke.equalsIgnoreCase("Angsuran 4")) {
            if (txtkodeangsuran.getText() != "") {
                com.yud.angsuran.AngsuranBulanan ab = new com.yud.angsuran.AngsuranBulanan();
                ab.setKodeans(kodeans);
                ab.setKodebp(kodebp);
                ab.setAngsuran4(jumlah);
                ab.setJumlah(Integer.parseInt(jumlah));
                ab.setTgl4(tanggalnya);
                ab.setTanggal(tanggalnya);
                ab.setAngsuranke(angsuranke);
                DaoFactory.getAngsuranBulananDao().resetSpaceDateAns(kodebp);
                DaoFactory.getAngsuranBulananDao().insertdetailangsuran(ab);
                DaoFactory.getAngsuranBulananDao().UpdateAngsuranBulanan4(ab);
                DaoFactory.getAngsuranDao().updateSisaAngsuran(kodebp);
            }
        } else if (angsuranke.equalsIgnoreCase("Angsuran 5")) {
            if (txtkodeangsuran.getText() != "") {
                com.yud.angsuran.AngsuranBulanan ab = new com.yud.angsuran.AngsuranBulanan();
                ab.setKodeans(kodeans);
                ab.setKodebp(kodebp);
                ab.setAngsuran5(jumlah);
                ab.setJumlah(Integer.parseInt(jumlah));
                ab.setTgl5(tanggalnya);
                ab.setTanggal(tanggalnya);
                ab.setAngsuranke(angsuranke);
                DaoFactory.getAngsuranBulananDao().resetSpaceDateAns(kodebp);
                DaoFactory.getAngsuranBulananDao().insertdetailangsuran(ab);
                DaoFactory.getAngsuranBulananDao().UpdateAngsuranBulanan5(ab);
                DaoFactory.getAngsuranDao().updateSisaAngsuran(kodebp);
            }
        } else if (angsuranke.equalsIgnoreCase("Angsuran 6")) {
            if (txtkodeangsuran.getText() != "") {
                com.yud.angsuran.AngsuranBulanan ab = new com.yud.angsuran.AngsuranBulanan();
                ab.setKodeans(kodeans);
                ab.setKodebp(kodebp);
                ab.setAngsuran6(jumlah);
                ab.setJumlah(Integer.parseInt(jumlah));
                ab.setTgl6(tanggalnya);
                ab.setTanggal(tanggalnya);
                ab.setAngsuranke(angsuranke);
                DaoFactory.getAngsuranBulananDao().resetSpaceDateAns(kodebp);
                DaoFactory.getAngsuranBulananDao().insertdetailangsuran(ab);
                DaoFactory.getAngsuranBulananDao().UpdateAngsuranBulanan6(ab);
                DaoFactory.getAngsuranDao().updateSisaAngsuran(kodebp);
            }
        } else if (angsuranke.equalsIgnoreCase("Angsuran 7")) {
            if (txtkodeangsuran.getText() != "") {
                com.yud.angsuran.AngsuranBulanan ab = new com.yud.angsuran.AngsuranBulanan();
                ab.setKodeans(kodeans);
                ab.setKodebp(kodebp);
                ab.setAngsuran7(jumlah);
                ab.setJumlah(Integer.parseInt(jumlah));
                ab.setTgl7(tanggalnya);
                ab.setTanggal(tanggalnya);
                ab.setAngsuranke(angsuranke);
                DaoFactory.getAngsuranBulananDao().resetSpaceDateAns(kodebp);
                DaoFactory.getAngsuranBulananDao().insertdetailangsuran(ab);
                DaoFactory.getAngsuranBulananDao().UpdateAngsuranBulanan7(ab);
                DaoFactory.getAngsuranDao().updateSisaAngsuran(kodebp);
            }
        } else if (angsuranke.equalsIgnoreCase("Angsuran 8")) {
            if (txtkodeangsuran.getText() != "") {
                com.yud.angsuran.AngsuranBulanan ab = new com.yud.angsuran.AngsuranBulanan();
                ab.setKodeans(kodeans);
                ab.setKodebp(kodebp);
                ab.setAngsuran8(jumlah);
                ab.setJumlah(Integer.parseInt(jumlah));
                ab.setTgl8(tanggalnya);
                ab.setTanggal(tanggalnya);
                ab.setAngsuranke(angsuranke);
                DaoFactory.getAngsuranBulananDao().resetSpaceDateAns(kodebp);
                DaoFactory.getAngsuranBulananDao().insertdetailangsuran(ab);
                DaoFactory.getAngsuranBulananDao().UpdateAngsuranBulanan8(ab);
                DaoFactory.getAngsuranDao().updateSisaAngsuran(kodebp);
            }
        } else if (angsuranke.equalsIgnoreCase("Angsuran 9")) {
            if (txtkodeangsuran.getText() != "") {
                com.yud.angsuran.AngsuranBulanan ab = new com.yud.angsuran.AngsuranBulanan();
                ab.setKodeans(kodeans);
                ab.setKodebp(kodebp);
                ab.setAngsuran9(jumlah);
                ab.setJumlah(Integer.parseInt(jumlah));
                ab.setTgl9(tanggalnya);
                ab.setTanggal(tanggalnya);
                ab.setAngsuranke(angsuranke);
                DaoFactory.getAngsuranBulananDao().resetSpaceDateAns(kodebp);
                DaoFactory.getAngsuranBulananDao().insertdetailangsuran(ab);
                DaoFactory.getAngsuranBulananDao().UpdateAngsuranBulanan9(ab);
                DaoFactory.getAngsuranDao().updateSisaAngsuran(kodebp);
            }
        } else if (angsuranke.equalsIgnoreCase("Angsuran 10")) {
            if (txtkodeangsuran.getText() != "") {
                com.yud.angsuran.AngsuranBulanan ab = new com.yud.angsuran.AngsuranBulanan();
                ab.setKodeans(kodeans);
                ab.setKodebp(kodebp);
                ab.setAngsuran10(jumlah);
                ab.setJumlah(Integer.parseInt(jumlah));
                ab.setTgl10(tanggalnya);
                ab.setTanggal(tanggalnya);
                ab.setAngsuranke(angsuranke);
                DaoFactory.getAngsuranBulananDao().resetSpaceDateAns(kodebp);
                DaoFactory.getAngsuranBulananDao().insertdetailangsuran(ab);
                DaoFactory.getAngsuranBulananDao().UpdateAngsuranBulanan10(ab);
                DaoFactory.getAngsuranDao().updateSisaAngsuran(kodebp);
            }
        }
        JOptionPane.showMessageDialog(null, "Angsuran Bulanan Berhasil Disimpan");
        new PrintReport("./report/ans bulanan.jasper", "nobp", kodebp);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        int row = TabelBP.getSelectedRow();
        if (row >= 0) {
            String kodebp = TabelBP.getValueAt(row, 9).toString();
            txtkodebp.setText(kodebp);
            Angsuran a = DaoFactory.getAngsuranDao().getAngsuranByKodeBP(kodebp);
            txtkodeangsuran.setText(a.getKodeAngsuran());
            jDesktopPane3.setVisible(false);
            jDesktopPane1.setVisible(true);
            txtkodebp.requestFocus();
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void tabelAngsurannyaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelAngsurannyaMouseClicked
        // TODO add your handling code here:
        txtFilter.setEnabled(true);
    }//GEN-LAST:event_tabelAngsurannyaMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String kode = txtkodebp.getText();
        if (kode != "") {
            showAngsuranBP(kode);
            BuktiPesanan bp = DaoFactory.getBuktiPesananDao().getBuktiPesananByKodeBP(kode);
            txtsisaberjalanlab.setText(String.valueOf(bp.getSisa2()));
            txtmakslab.setText(String.valueOf(bp.getSisa()));
            txttotalbplab.setText(String.valueOf(bp.getTotal()));
            if (!txtkodebp.getText().equalsIgnoreCase("")) {
                txttotalangsuranlab.setText(String.valueOf(DaoFactory.getAngsuranDao().getTotalAngsuranByKodeBp(kode)));
                txtbulannalab.setText(String.valueOf(bp.getAngsuran()));
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String kode = txtkodebp.getText();
        if (kode != "") {
            int opsi = JOptionPane.showConfirmDialog(null, "Yakin akan mencetak data ?");
            if (opsi == 0) {
                new PrintReport("./report/ans bulanan.jasper", "nobp", kode);
            }

        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        clearfild();
        showAngsuranBP("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        clearfild();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtkodebpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtkodebpMouseClicked
        // TODO add your handling code here:
        String kode = txtkodebp.getText();
        BuktiPesanan bp = DaoFactory.getBuktiPesananDao().getBuktiPesananByKodeBP(kode);
        txtsisaberjalanlab.setText(String.valueOf(bp.getSisa2()));
        txtmakslab.setText(String.valueOf(bp.getSisa()));
        txttotalbplab.setText(String.valueOf(bp.getTotal()));
        if (!txtkodebp.getText().equalsIgnoreCase("")) {
            txttotalangsuranlab.setText(String.valueOf(DaoFactory.getAngsuranDao().getTotalAngsuranByKodeBp(kode)));
            txtbulannalab.setText(String.valueOf(bp.getAngsuran()));
        }
    }//GEN-LAST:event_txtkodebpMouseClicked

    private void txtkodebpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkodebpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkodebpActionPerformed

    private void showBP() {
        BuktiPesananTabelModel bptm = new BuktiPesananTabelModel(DaoFactory.getBuktiPesananDao().getAllBuktiPesanan());
        sorter2 = new TableRowSorter<TableModel>(bptm);
        TabelBP.setRowMargin(0);
        sorter = new TableRowSorter<TableModel>(bptm);
        TabelBP.setModel(bptm);
        TabelBP.setRowSorter(sorter2);
        //TabelBarang.setAutoResizeMode(0);
        TabelBP.getColumnModel().getColumn(0).setPreferredWidth(10);
        TabelBP.getColumnModel().getColumn(1).setPreferredWidth(80);
    }

    private void showAngsuranBP(String kode) {
        AngsuranBulananTabelModel bptm = new AngsuranBulananTabelModel(DaoFactory.getAngsuranBulananDao().getAllAngsuranBulananByKodeBP(kode));
        sorter2 = new TableRowSorter<TableModel>(bptm);
        tabelAngsurannya.setRowMargin(0);
        sorter = new TableRowSorter<TableModel>(bptm);
        tabelAngsurannya.setModel(bptm);
        tabelAngsurannya.setRowSorter(sorter2);
        //TabelBarang.setAutoResizeMode(0);
        tabelAngsurannya.getColumnModel().getColumn(0).setPreferredWidth(10);
        tabelAngsurannya.getColumnModel().getColumn(1).setPreferredWidth(80);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AngsuranBulanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AngsuranBulanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AngsuranBulanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AngsuranBulanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AngsuranBulanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelBP;
    private javax.swing.JComboBox<String> comboAngsuran;
    private javax.swing.JTextField filterBP;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelAngsurannya;
    private com.toedter.calendar.JDateChooser tglAngsuran;
    private javax.swing.JTextField txtFilter;
    private javax.swing.JLabel txtbulannalab;
    private javax.swing.JTextField txtjumlah;
    private javax.swing.JTextField txtkodeangsuran;
    private javax.swing.JTextField txtkodebp;
    private javax.swing.JLabel txtmakslab;
    private javax.swing.JLabel txtsisaberjalanlab;
    private javax.swing.JLabel txttotalangsuranlab;
    private javax.swing.JLabel txttotalbplab;
    // End of variables declaration//GEN-END:variables
}
