/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.yud.ui;

import com.init.tools.DaoFactory;
import com.init.tools.PrintReport;
import com.yud.bstu.STUTabelModel;
import com.yud.bstu.SerahTerimaUang;
import com.yud.bstu.SerahTerimaUangTabelModel;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.RowSorter;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author legollas
 */
public class BSTUang extends javax.swing.JFrame {

    private RowSorter<TableModel> sorter = null;
    private TableRowSorter<TableModel> sorter2 = null;
    private RowSorter<TableModel> sorter3 = null;
    private TableRowSorter<TableModel> sorter4 = null;

    /**
     * Creates new form BSTUang
     */
    public BSTUang() {
        initComponents();
        loadform();
        setLocationRelativeTo(null);
    }

    private void loadform() {
        txtNoFaktur.setText(DaoFactory.getIDUrutBSTU());
        DaoFactory.getSerahTerimaUangDao().truncateTempBSTU();
        cekMasuk.setSelected(true);
        radAngsuran.setSelected(true);
        tglBSTU.setDate(new GregorianCalendar().getTime());
        jDesktopPane1.setVisible(true);
        jDesktopPane2.setVisible(false);
    }

    private void clearfield() {
        txtNama.setText("");
        txtUraian.setText("");
        txtJumlah.setText("");
        txtKeterangan.setText("");
        txtDiserahkan.setText("");
        cekMasuk.setSelected(true);
        radAngsuran.setSelected(true);
        loadform();
    }

    private void showBSTUALL() {
        STUTabelModel model = new STUTabelModel(DaoFactory.getSerahTerimaUangDao().getAllBSTU());
        sorter4 = new TableRowSorter<TableModel>(model);
        tabelBstuAll.setRowMargin(0);
        tabelBstuAll.setModel(model);
        tabelBstuAll.setRowSorter(sorter4);
        //TabelBarang.setAutoResizeMode(0);
        tabelBstuAll.getColumnModel().getColumn(0).setPreferredWidth(10);
        tabelBstuAll.getColumnModel().getColumn(1).setPreferredWidth(60);
        tabelBstuAll.getColumnModel().getColumn(2).setPreferredWidth(200);
        tabelBstuAll.getColumnModel().getColumn(3).setPreferredWidth(80);
    }

    private void showBSTUTemp() {
        SerahTerimaUangTabelModel bstu = new SerahTerimaUangTabelModel(DaoFactory.getSerahTerimaUangDao().GetAllTempBSTU());
        sorter2 = new TableRowSorter<TableModel>(bstu);
        tabelbstu.setRowMargin(0);
        sorter = new TableRowSorter<TableModel>(bstu);
        tabelbstu.setModel(bstu);
        tabelbstu.setRowSorter(sorter2);
        //TabelBarang.setAutoResizeMode(0);
        tabelbstu.getColumnModel().getColumn(0).setPreferredWidth(10);
        tabelbstu.getColumnModel().getColumn(1).setPreferredWidth(60);
        tabelbstu.getColumnModel().getColumn(2).setPreferredWidth(200);
        tabelbstu.getColumnModel().getColumn(3).setPreferredWidth(80);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jenisradio = new javax.swing.ButtonGroup();
        jeniscek = new javax.swing.ButtonGroup();
        jSeparator2 = new javax.swing.JSeparator();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNoFaktur = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtUraian = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtJumlah = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtKeterangan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelbstu = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        butDafBSTU = new javax.swing.JButton();
        cekMasuk = new javax.swing.JCheckBox();
        cekKeluar = new javax.swing.JCheckBox();
        radAngsuran = new javax.swing.JRadioButton();
        radTunai = new javax.swing.JRadioButton();
        radKomisi = new javax.swing.JRadioButton();
        radLainnya = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        txtDiserahkan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtnamadetil = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        tglBSTU = new com.toedter.calendar.JDateChooser();
        jButton5 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtTotalnya = new javax.swing.JLabel();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        filterText2 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelBstuAll = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("BUKTI SERAH TERIMA UANG");

        txtNoFaktur.setText("............................");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(376, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(173, 173, 173)
                .addComponent(txtNoFaktur, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNoFaktur)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDesktopPane1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 50));

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));

        jLabel2.setText("Diterima Oleh");

        jLabel3.setText("Uraian");

        jLabel4.setText("Jumlah (Rp)");

        txtJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahActionPerformed(evt);
            }
        });
        txtJumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtJumlahKeyPressed(evt);
            }
        });

        jLabel5.setText("Keterangan");

        tabelbstu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No", "Nama", "Uraian", "Jumlah", "Keterangan"
            }
        ));
        jScrollPane1.setViewportView(tabelbstu);

        jButton1.setText("Keluar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Simpan");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Batal");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        butDafBSTU.setText("Daftar BSTU");
        butDafBSTU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butDafBSTUActionPerformed(evt);
            }
        });

        jeniscek.add(cekMasuk);
        cekMasuk.setText("Masuk");

        jeniscek.add(cekKeluar);
        cekKeluar.setText("Keluar");

        jenisradio.add(radAngsuran);
        radAngsuran.setText("Angsuran");

        jenisradio.add(radTunai);
        radTunai.setText("Tunai");

        jenisradio.add(radKomisi);
        radKomisi.setText("Komisi");

        jenisradio.add(radLainnya);
        radLainnya.setText("Lainnya");

        jLabel6.setText("Diserahkan Oleh");

        jLabel7.setText("Nama");

        jLabel8.setText("Tanggal");

        jButton5.setText("OK");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel9.setText("Total");

        txtTotalnya.setText("Rp.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNama, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(txtDiserahkan))
                        .addGap(81, 81, 81)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(radAngsuran)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radTunai)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radKomisi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radLainnya))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cekMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cekKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(111, 111, 111)
                                .addComponent(jLabel8)
                                .addGap(36, 36, 36)
                                .addComponent(tglBSTU, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 191, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtnamadetil, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addGap(10, 10, 10)
                                .addComponent(txtUraian, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtKeterangan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTotalnya, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(butDafBSTU)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)))
                        .addGap(28, 28, 28)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cekMasuk)
                        .addComponent(cekKeluar)
                        .addComponent(jLabel8))
                    .addComponent(tglBSTU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDiserahkan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radTunai)
                    .addComponent(radKomisi)
                    .addComponent(radLainnya)
                    .addComponent(radAngsuran))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUraian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(txtnamadetil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2)
                        .addComponent(jButton3)
                        .addComponent(butDafBSTU))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(txtTotalnya)))
                .addGap(7, 7, 7))
        );

        jDesktopPane1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1080, 390));

        jDesktopPane2.setBackground(new java.awt.Color(204, 204, 204));
        jDesktopPane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 153));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("DAFTAR BUKTI SERAH TERIMA UANG");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(379, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(356, 356, 356))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDesktopPane2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 50));

        jLabel11.setText("Cari");

        filterText2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                filterText2MouseClicked(evt);
            }
        });
        filterText2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filterText2KeyReleased(evt);
            }
        });

        tabelBstuAll.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabelBstuAll);

        jButton6.setText("Tutup");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Pilih");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton4.setText("Cetak");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1050, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(filterText2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(filterText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDesktopPane2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1070, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1067, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jDesktopPane2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jDesktopPane2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
            String kodefaktur = txtNoFaktur.getText();
            String namapenerima = txtNama.getText();
            String namapenyerah = txtDiserahkan.getText();
            String jumlah = txtTotalnya.getText();
            String uraian = txtUraian.getText();
            DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            String tglnya = df.format(tglBSTU.getDate());
            String statuscek = "";
            if (cekMasuk.isSelected() == true) {
                statuscek = "Masuk";
            } else if (cekKeluar.isSelected() == true) {
                statuscek = "Keluar";
            }
            String jeniskeluar = "";
            if (radAngsuran.isSelected() == true) {
                jeniskeluar = "Angsuran";
            } else if (radKomisi.isSelected() == true) {
                jeniskeluar = "Komisi";
            } else if (radTunai.isSelected() == true) {
                jeniskeluar = "Tunai";
            } else if (radLainnya.isSelected() == true) {
                jeniskeluar = "Lainnya";
            }
            SerahTerimaUang stu = new SerahTerimaUang();
            stu.setKodeBSTU(kodefaktur);
            stu.setNama(namapenerima);//penerima
            stu.setDiserahkan(namapenyerah);
            stu.setJenisbstu(jeniskeluar);
            stu.setStatus(statuscek);
            stu.setJumlah(Integer.parseInt(jumlah));
            stu.setTanggal(tglnya);
            stu.setUraian(uraian);
            DaoFactory.getSerahTerimaUangDao().insertBSTU(stu);
            DaoFactory.insertUrutBSTU(txtNoFaktur.getText());
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            new PrintReport("./report/serahterimauang.jasper", "kodefaktur", kodefaktur);
            clearfield();
            DaoFactory.getSerahTerimaUangDao().truncateTempBSTU();
            loadform();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
            Logger.getLogger(BSTUang.class.getName()).log(Level.SEVERE, null, ex);
        }
        clearfield();
        DaoFactory.getSerahTerimaUangDao().truncateTempBSTU();
        loadform();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtJumlahKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJumlahKeyPressed
        // TODO add your handling code here:
        String nama = txtnamadetil.getText();
        String uraian = txtUraian.getText();
        String keterangan = txtKeterangan.getText();
        String jumlah = txtJumlah.getText();
        String kode = txtNoFaktur.getText();
        int jumlahnya = Integer.parseInt(jumlah);
        SerahTerimaUang stu = new SerahTerimaUang();
        stu.setNama(nama);
        stu.setUraian(uraian);
        stu.setKeterangan(keterangan);
        stu.setJumlah(jumlahnya);
        stu.setKodeBSTU(kode);
        clearfielddetil();
        DaoFactory.getSerahTerimaUangDao().InsertTempBSTU(stu);
        showBSTUTemp();
        txtTotalnya.setText(String.valueOf(DaoFactory.getSerahTerimaUangDao().getSUMTemp(kode)));   
    }//GEN-LAST:event_txtJumlahKeyPressed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String nama = txtnamadetil.getText();
        String uraian = txtUraian.getText();
        String keterangan = txtKeterangan.getText();
        String jumlah = txtJumlah.getText();
        String kode = txtNoFaktur.getText();
        int jumlahnya = Integer.parseInt(jumlah);
        SerahTerimaUang stu = new SerahTerimaUang();
        stu.setNama(nama);
        stu.setUraian(uraian);
        stu.setKeterangan(keterangan);
        stu.setJumlah(jumlahnya);
        stu.setKodeBSTU(kode);
        clearfielddetil();
        DaoFactory.getSerahTerimaUangDao().InsertTempBSTU(stu);
        showBSTUTemp();
        txtTotalnya.setText(String.valueOf(DaoFactory.getSerahTerimaUangDao().getSUMTemp(kode)));
    }//GEN-LAST:event_jButton5ActionPerformed

    private void clearfielddetil() {
        txtnamadetil.setText("");
        txtUraian.setText("");
        txtKeterangan.setText("");
        txtJumlah.setText("");
    }

    private void cleartfieldall() {
        txtNama.setText("");
        txtDiserahkan.setText("");
        cekMasuk.setSelected(true);
        radAngsuran.setSelected(true);
        tglBSTU.setDate(new GregorianCalendar().getTime());
        txtnamadetil.setText("");
        txtUraian.setText("");
        txtKeterangan.setText("");
        txtJumlah.setText("");
        txtNoFaktur.setText(DaoFactory.getIDUrutBSTU());
        DaoFactory.getSerahTerimaUangDao().truncateTempBSTU();
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        cleartfieldall();
        loadform();
        showBSTUTemp();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void butDafBSTUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butDafBSTUActionPerformed
        // TODO add your handling code here:
        showBSTUALL();
        jDesktopPane1.setVisible(false);
        jDesktopPane2.setVisible(true);
    }//GEN-LAST:event_butDafBSTUActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        jDesktopPane2.setVisible(false);
        jDesktopPane1.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void filterText2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filterText2MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_filterText2MouseClicked

    private void filterText2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filterText2KeyReleased
        // TODO add your handling code here:
        String text = filterText2.getText();
        if (text.length() == 0) {
            sorter4.setRowFilter(null);
        } else {
            System.out.println("y");
            sorter4.setRowFilter(RowFilter.regexFilter(text));
        }
    }//GEN-LAST:event_filterText2KeyReleased

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        int wor = tabelBstuAll.getSelectedRow();
        if (wor >= 0) {
            String kode = tabelBstuAll.getValueAt(wor, 1).toString();
            txtNoFaktur.setText(kode);
            DaoFactory.getSerahTerimaUangDao().truncateTempBSTU();
            SerahTerimaUang stu = DaoFactory.getSerahTerimaUangDao().getSerahTerimaByKode(kode);
            txtNama.setText(stu.getNama());
            txtDiserahkan.setText(stu.getDiserahkan());
            DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            try {
                tglBSTU.setDate(df.parse(stu.getTanggal()));
            } catch (ParseException ex) {
                Logger.getLogger(BSTUang.class.getName()).log(Level.SEVERE, null, ex);
            }
            String status = stu.getStatus();
            if (status.equalsIgnoreCase("masuk")) {
                cekMasuk.setSelected(true);
            } else if (status.equalsIgnoreCase("keluar")) {
                cekKeluar.setSelected(true);
            }
            String jenisnya = stu.getJenisbstu();
            if (jenisnya.equalsIgnoreCase("Angsuran")) {
                radAngsuran.setSelected(true);
            } else if (jenisnya.equalsIgnoreCase("Tunai")) {
                radTunai.setSelected(true);
            } else if (jenisnya.equalsIgnoreCase("Komisi")) {
                radKomisi.setSelected(true);
            } else if (jenisnya.equalsIgnoreCase("Lainnya")) {
                radLainnya.setSelected(true);
            }
            DaoFactory.getSerahTerimaUangDao().lookBSTUDetailToTemp(kode);
            jDesktopPane2.setVisible(false);
            jDesktopPane1.setVisible(true);
            showBSTUTemp();
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int wor = tabelBstuAll.getSelectedRow();
        if (wor >= 0) {
            String kode = tabelBstuAll.getValueAt(wor, 1).toString();
            System.out.println(kode);
            new PrintReport("./report/serahterimauang.jasper", "kodefaktur", kode);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BSTUang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BSTUang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BSTUang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BSTUang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BSTUang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butDafBSTU;
    private javax.swing.JCheckBox cekKeluar;
    private javax.swing.JCheckBox cekMasuk;
    private javax.swing.JTextField filterText2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.ButtonGroup jeniscek;
    private javax.swing.ButtonGroup jenisradio;
    private javax.swing.JRadioButton radAngsuran;
    private javax.swing.JRadioButton radKomisi;
    private javax.swing.JRadioButton radLainnya;
    private javax.swing.JRadioButton radTunai;
    private javax.swing.JTable tabelBstuAll;
    private javax.swing.JTable tabelbstu;
    private com.toedter.calendar.JDateChooser tglBSTU;
    private javax.swing.JTextField txtDiserahkan;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtKeterangan;
    private javax.swing.JTextField txtNama;
    private javax.swing.JLabel txtNoFaktur;
    private javax.swing.JLabel txtTotalnya;
    private javax.swing.JTextField txtUraian;
    private javax.swing.JTextField txtnamadetil;
    // End of variables declaration//GEN-END:variables
}
